---
- name: Download mackerel agent archive
  get_url:
    url: https://github.com/mackerelio/mackerel-agent/releases/download/{{ mackerel_agent_version }}/mackerel-agent_linux_arm.tar.gz
    dest: /tmp/mackerel-agent{{ mackerel_agent_version }}.tar.gz

- name: Unpack archive
  unarchive:
    src: /tmp/mackerel-agent{{ mackerel_agent_version }}.tar.gz
    dest: /tmp/
    remote_src: True

- name: Install mackerel agent
  shell: "mv /tmp/mackerel-agent_linux_arm /usr/local/mackerel-agent/ && rm -rf /usr/local/mackerel-agent/mackerel-agent_linux_arm"

- name: Create directory for mackerelio repository
  file:
    path: /home/pi/go/src/github.com/mackerelio
    state: directory
    mode: 0755

- name: git clone mackerel plugin (and its dependencies)
  git:
    repo: https://github.com/mackerelio/{{ item }}
    dest: /home/pi/go/src/github.com/mackerelio/{{ item }}
  with_items:
    - golib
    - go-mackerel-plugin-helper
    - mackerel-agent
    - mackerel-agent-plugins

- name: Create directory for dependent repository
  file:
    path: /home/pi/go/src/github.com/urfave
    state: directory
    mode: 0755

- name: git clone dependency
  git:
    repo: https://github.com/urfave/cli
    dest: /home/pi/go/src/github.com/urfave/cli

- name: Create mackerel-agent plugin directory
  file:
    path: /usr/local/mackerel-agent/plugin
    state: directory
    mode: 0755

- name: Build mackerel-plugin and install
  shell: "GOPATH=/home/pi/go /usr/local/go/bin/go build && cp ./{{ item }} /usr/local/mackerel-agent/plugin/"
  args:
    chdir: /home/pi/go/src/github.com/mackerelio/mackerel-agent-plugins/{{ item }}
  with_items:
    - mackerel-plugin-inode
    - mackerel-plugin-linux
    - mackerel-plugin-uptime

- name: Create mackerel-agent configuration directory
  file:
    path: /etc/mackerel-agent
    state: directory
    mode: 0755

- name: Initialize mackerel-agent configuration
  template:
    src: mackerel-agent.conf.j2
    dest: /etc/mackerel-agent/mackerel-agent.conf

- name: Initialize mackerel-agent service
  template:
    src: mackerel-agent.service.j2
    dest: /etc/systemd/system/mackerel-agent.service

- name: Start mackrel-agent
  systemd:
    name: mackerel-agent
    enabled: yes
    state: started

